name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: download Norm
        run: pip install norminette
      - name: install x11
        run: sudo apt-get update && sudo apt-get install -y \
          libx11-dev \
          libxext-dev \
          libxrandr-dev \
          libxinerama-dev \
          libxcursor-dev \
          libxi-dev

      - name: Norm
        run: norminette src/ include/ main.c

      - name: Build
        run: make

