name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Norminette
        run: pip install norminette

      - name: Install dependencies (X11 + build tools)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential \
            libx11-dev \
            libxext-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxi-dev \
            libbsd-dev

      - name: Norm check
        run: norminette src/ include/ main.c

      - name: Build
        run: make
