name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: download Norm
        run: pip install norminette

      - name: Norm
        run: norminette

      - name: Build
        run: make

